### ISSUE TITLE
Repository points to home furnishing website

### ISSUE THREAD

**Issue by paulmasson** [mathifold/mathifold#74]
Does the mathematics website exist somewhere?

**Comment by juanjomadrigal** [comment]
Oh, sorry... It has been migrated to tungsteno.io (see also https://github.com/TungstenHub). I'll change the links right away. Thank you very much!!

**Comment by juanjomadrigal** [comment]
btw @paulmasson if you like three.js, see http://tungsteno.io/inside/#nav-1-threejs-contest - until July 15th !!
